name: mfr_detect
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - ultralytics==8.4.14
      - segmentation-models-pytorch==0.5.0
      - albumentations==2.0.8
      - timm==1.0.24
      - opencv-python-headless==4.13.0.92
      - pandas==2.3.3
      - scipy==1.15.3
